name: Pull Request push
run-name: ${{ github.ref }} by ${{ github.actor }} - Pull Request push
on: [push]
jobs:
  coding-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Check fmt
        run: |
          cd .devenv && make fmt && git --no-pager diff --name-only --exit-code
      - name: Check goimports
        run: |
          cd .devenv && make imports && git --no-pager diff --name-only --exit-code
      - name: Lint router
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
          working-directory: router
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Lint adapters/kafka
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
          working-directory: adapters/kafka
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Lint adapters/redis
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
          working-directory: adapters/redis
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Lint example/api-server
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
          working-directory: example/api-server
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Lint example/tor
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
          working-directory: example/tor
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Test
        run: |
          cd .devenv && make test

